[package]
name = "drg-attacks"
version = "0.1.0"
authors = ["nalos"]
edition = "2018"

[dependencies]
rand = "0.7"
rand_chacha = "0.2.1"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.3.1"
rayon = "1.2.0"
